### ISSUE TITLE
Change "Cooperative Statue URL" to "Platform Terms & Conditions"

### ISSUE THREAD

**Issue by mj-ampnet** [AMPnet/ampnet-crowdfunding-frontend#175]

**Comment by mightymatth** [comment]
That term `cooperative statute` or `statute` appears, as far as I see, in two places:

1. Platform configuration (the place you are pointing to)
2. User verification checkbox
* current title: `"Statute confirmation"`
  * proposal: `"Accept Platform Terms & Conditions"`
* current checkbox notice: `"Check here to indicate that you have read and agree to the terms of the | {{ coopName }} Statute |"`
  * proposal: `"Check here to indicate that you have read and agree to the | {{ coopName }} Terms & Conditions |"`
